### ISSUE TITLE
Addition of support for timeseries AM times

### ISSUE THREAD

**Issue by pwolfram** [pwolfram/mpas_xarray#4]
Following conversations with @milenaveneziani it would be good to support time-coordinate output from the MPAS-O timeseries AM, e.g., populating the time dimension from `timeseriesstats_avg_daysSinceStartOfSim`

**Comment by milenaveneziani** [comment]
The current time-coordinate support for MPAS time series is based on 'xtime'. But this string variable is not representative of the correct time stamp for fields that have been processed by the time series stats AM. Instead, the correct representation of this time stamp is the mean time between tavg_start and tavg_end, where tavg_start:tavg_end is the time period over which the time series stats AM has been applied.
I feel like we have two options for supporting the time-coordinate of timeSeriesStats_avg MPAS output:
1) base it on the variable timeSeriesStats_avg_daysSinceStartOfSim, which is basically 0.5*(tavgEnd-tavgStart), where tavgStart and tavgEnd are expressed in number of days since start of simulation. This can be done immediately (I have personally implemented it in one of my scripts as a temporary fix), but has the disadvantage that the user **has** to have the variable daysSinceStartOfSim in the time series stats AM output stream for things to work;
2) base it on 'xtimeStart' and 'xtimeEnd' (with meaning similar to tavgStart and tavgEnd), which are variables that will be added to the time series stats AM soon.

Do people have preferences for either 1) or 2)?

**Comment by pwolfram** [comment]
@milenaveneziani, I'm thinking it may be better to implement the solution that works for now and then adapt it in the future once the time issue is sorted out with the AM.  @jonwoodring, are you ok with this for now?  I suspect we may also talk about this at the meeting on Monday.

Also, @milenaveneziani, is it possible to submit a PR with a very small example of a few dataset files that can be used to demonstrate that any changes we make work?

**Comment by milenaveneziani** [comment]
yes, it is possible to submit a PR. Let us talk more on Monday.
thanks for the prompt feedback.

**Comment by ghost** [comment]
Sure, what works for now is fine with me.

My plan is to add 'xtime_start' and 'xtime_end'.

Also, for future reference, the names of the outputs are going to be 'time_avg_foo', 'time_min_bar', 'time_max_baz' by changing 'timeSeriesStats_' to 'time_'. It's because the names are getting long through chaining the operations together, and likely going to run into the 64 character limit. 

Down the road, I'm probably going to need to add the ability rename/rebind variables to names.

Because this is going to happen:
ssh => regional stats => reg_labradorSea_avg_ssh => time series => time_avg_reg_labradorSea_avg_ssh

**Comment by ghost** [comment]
And it gets worse with something like activeTracers:

activeTracers => regional stats => reg_labradorSea_avg_activeTracers_temperature => time series => time_avg_reg_labradorSea_avg_activeTracers_temperature

**Comment by pwolfram** [comment]
Thanks for the feedback @jonwoodring and @milenaveneziani, see @milenaveneziani 's PR #6

**Comment by milenaveneziani** [comment]
@pwolfram: I have another question/suggestion regarding the preprocess_mpas wrapper: could we make yearoffset as an option? (This would also answer some of your questions on PR#6). We basically would want yearoffset (and monthoffset, dayoffset) to be the following, for example:
1) yearoffset=1849, monthoffset=12, dayoffset=31 for time-slice experiments with fixed pre-indutrial (1850) conditions;
2) yearoffset=1999, monthoffset=12, dayoffset=31 for time-slice experiments with fixed present-day (2000) conditions.
3) yearoffset=0, monthoffset=12, dayoffset=31 for transient experiments with varying conditions (no need for a year offset here because dates will fall into the xarray comfort zone)
What do you think?

**Comment by pwolfram** [comment]
@milenaveneziani, I think this makes a lot of sense and is essentially what I was thinking about although the idea to have different wrappers for different configurations is a good one.  We just want to make sure to package the code in such a way that it is clear and code is not duplicated, but this is an implementation issue.

We could then have "thin-wrappers" for each of these three conditions that feed the appropriate starting dates into a base wrapper.

**Comment by pwolfram** [comment]
@milenaveneziani, have we adequately resolved this for now?  If so, I'll close the issue.

**Comment by milenaveneziani** [comment]
@pwolfram: I think this can be closed after we merge #8.
We should remind ourselves though that the timeSeriesStats preprocessing step will need to be revised once xtime_start and xtime_end (instead of xtime) will become default output of the timeSeriesStats AM.

**Comment by pwolfram** [comment]
@milenaveneziani, thanks!

**Comment by pwolfram** [comment]
See https://github.com/MPAS-Dev/MPAS/pull/945, may need to reopen or start a new issue-- thoughts on this @milenaveneziani?
